# Generated by Django 4.2.5 on 2023-10-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-placeholder.jpg', null=True, upload_to='profiles/'),
        ),
    ]
